import { Inter } from "next/font/google"; // Import the Inter font
import type { Metadata } from "next";
import  Navbar  from '@/Clients/NavBar'


// Load the Inter font with optional settings
const inter = Inter({
  subsets: ['latin'], // Include additional subsets if necessary
  variable: '--font-inter', // Create a custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`} // Apply the font variable
      >
        < Navbar />
        {children}
      </body>
    </html>
  );
}
